#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Teleco.Resource", IsApplication=true)]

namespace Teleco
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int fbx_0 = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int fbx_1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int fbx_2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int fbx_3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int fbx_4 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int fbx_5 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int fbx_6 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int fbx_7 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int fbx_8 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int fbx_9 = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int fbx_av = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int fbx_back = 2131034126;
			
			// aapt resource value: 0x7f05001d
			public const int fbx_chanm = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int fbx_chanp = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int fbx_down = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int fbx_enter = 2131034130;
			
			// aapt resource value: 0x7f050020
			public const int fbx_forward = 2131034144;
			
			// aapt resource value: 0x7f050017
			public const int fbx_free = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int fbx_info = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int fbx_left = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int fbx_menu = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int fbx_mute = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int fbx_play = 2131034143;
			
			// aapt resource value: 0x7f050003
			public const int fbx_power = 2131034115;
			
			// aapt resource value: 0x7f05001c
			public const int fbx_record = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int fbx_rewind = 2131034142;
			
			// aapt resource value: 0x7f050013
			public const int fbx_right = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int fbx_search = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int fbx_teleco = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int fbx_up = 2131034127;
			
			// aapt resource value: 0x7f05001b
			public const int fbx_volm = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int fbx_volp = 2131034136;
			
			// aapt resource value: 0x7f05002d
			public const int kodi_back = 2131034157;
			
			// aapt resource value: 0x7f050034
			public const int kodi_down = 2131034164;
			
			// aapt resource value: 0x7f050027
			public const int kodi_firstpage = 2131034151;
			
			// aapt resource value: 0x7f050035
			public const int kodi_info = 2131034165;
			
			// aapt resource value: 0x7f05002a
			public const int kodi_lastpage = 2131034154;
			
			// aapt resource value: 0x7f050030
			public const int kodi_left = 2131034160;
			
			// aapt resource value: 0x7f050033
			public const int kodi_menu = 2131034163;
			
			// aapt resource value: 0x7f050038
			public const int kodi_mute = 2131034168;
			
			// aapt resource value: 0x7f05002c
			public const int kodi_nextletter = 2131034156;
			
			// aapt resource value: 0x7f050031
			public const int kodi_ok = 2131034161;
			
			// aapt resource value: 0x7f05002b
			public const int kodi_pagedown = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int kodi_pageup = 2131034152;
			
			// aapt resource value: 0x7f05003e
			public const int kodi_playpause = 2131034174;
			
			// aapt resource value: 0x7f050029
			public const int kodi_prevletter = 2131034153;
			
			// aapt resource value: 0x7f05002f
			public const int kodi_quit = 2131034159;
			
			// aapt resource value: 0x7f050032
			public const int kodi_right = 2131034162;
			
			// aapt resource value: 0x7f05003f
			public const int kodi_skipnext = 2131034175;
			
			// aapt resource value: 0x7f05003d
			public const int kodi_skipprevious = 2131034173;
			
			// aapt resource value: 0x7f050036
			public const int kodi_start = 2131034166;
			
			// aapt resource value: 0x7f05003a
			public const int kodi_stepback = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int kodi_stepforward = 2131034172;
			
			// aapt resource value: 0x7f05003b
			public const int kodi_stop = 2131034171;
			
			// aapt resource value: 0x7f050026
			public const int kodi_teleco = 2131034150;
			
			// aapt resource value: 0x7f05002e
			public const int kodi_up = 2131034158;
			
			// aapt resource value: 0x7f050037
			public const int kodi_volumedown = 2131034167;
			
			// aapt resource value: 0x7f050039
			public const int kodi_volumeup = 2131034169;
			
			// aapt resource value: 0x7f050000
			public const int main_view = 2131034112;
			
			// aapt resource value: 0x7f050025
			public const int tv_free = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int tv_on = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int tv_rpi = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int tv_standby = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int tv_teleco = 2131034145;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
